language: php
services:
  - mysql
branches:
  only:
  - L55
php:
  - '7.1'
  - nightly
git:
  submodules: false
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql -e 'set GLOBAL default_storage_engine=`InnoDb`;'
  - mysql -e 'create database circle_test;'
  - sudo service mysql restart
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - sudo echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-keyscan -H -t rsa,dsa github.com >> ~/.ssh/known_hosts
  - git submodule sync
  - git submodule update --init
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - sudo chmod -R 755 storage bootstrap/cache
  - composer dump-autoload -o
script:
  - vendor/bin/phpunit --testsuite Foundation,AppUnit,AppHTTP
