version: "2"

services:
  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
      - default
  db:
    image: mysql:5.7
    ports:
      - "8806:3306"
    environment:
      MYSQL_DATABASE: collejo
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker/dbdata:/var/lib/mysql/
      - ./docker/my.cnf:/etc/mysql/my.cnf
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: docker/app.docker
    volumes:
      - .:/var/www
    networks:
      - internal

networks:
  internal:
    driver: bridge