# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.14-fpm-node-browsers
      - image: circleci/mysql:latest

    working_directory: ~/repo

    steps:
      - run:
          name: Install libzip
          command: sudo apt-get install -y libzip-dev
      - run:
          name: Install PHP Zip
          command: sudo docker-php-ext-install zip
      - run:
          name: Install PHP MySql
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: Install Mysql Client
          command: sudo apt-get install -y mysql-client
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Sync Git Submodules
          command: git submodule sync
      - run:
          name: Update Git Submodules
          command: git submodule update --init
      - run:
          name: Set access to bootstrap dir
          command: sudo chmod -R 755 storage bootstrap/cache
      - run: cp tests/test.env .env
      - run: composer install --prefer-dist
      - run: composer dump-autoload -o
      - run: mkdir -p build/logs
      - run: npm install
      - run: php artisan asset:routes
      - run: php artisan asset:trans
      - run: npm run prod
      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      - store_artifacts:
          path: tests/Browser